//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeetingReservation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participant
    {
        public string ParticipantID { get; set; }
        public string MailAdress { get; set; }
        public string PhoneNumber { get; set; }
        public string NameSurname { get; set; }
        public int ReservationID { get; set; }
    
        public virtual Reservation Reservation { get; set; }
    }
}
