//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeetingReservation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reservation()
        {
            this.Participants = new HashSet<Participant>();
        }
    
        public int ReservationID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string StartTime { get; set; }
        public int MeetingRoomID { get; set; }
        public string EndTime { get; set; }
        public Nullable<int> TimeInterval { get; set; }
    
        public virtual MeetingRoom MeetingRoom { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Participant> Participants { get; set; }
    }
}
